/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Pin_LED_aliases.h"
#include "Pin_LED.h"
#include "Pin_StepperCLK_aliases.h"
#include "Pin_StepperCLK.h"
#include "Pin_StepperDIR_aliases.h"
#include "Pin_StepperDIR.h"
#include "Pin_StepperEN_aliases.h"
#include "Pin_StepperEN.h"
#include "PGA_Photo.h"
#include "Pin_StepperSLEEP_aliases.h"
#include "Pin_StepperSLEEP.h"
#include "Pin_StepperRES_aliases.h"
#include "Pin_StepperRES.h"
#include "Analog_Digital_Converter.h"
#include "Pin_StepperMS3_aliases.h"
#include "Pin_StepperMS3.h"
#include "Pin_StepperMS2_aliases.h"
#include "Pin_StepperMS2.h"
#include "Pin_StepperMS1_aliases.h"
#include "Pin_StepperMS1.h"
#include "Pin_PhotoDiode_aliases.h"
#include "Pin_PhotoDiode.h"
#include "TIA_1.h"
#include "Pin_LaserEN1_aliases.h"
#include "Pin_LaserEN1.h"
#include "UART_TFT.h"
#include "Pin_LaserEN2_aliases.h"
#include "Pin_LaserEN2.h"
#include "Interr_TFT.h"
#include "timer_clock.h"
#include "Timer1.h"
#include "Timer1_Function.h"
#include "LED_slider_val_sent_aliases.h"
#include "LED_slider_val_sent.h"
#include "LED_slider_val_received_aliases.h"
#include "LED_slider_val_received.h"
#include "LED_Measurement_running_aliases.h"
#include "LED_Measurement_running.h"
#include "Emul_EEPROM.h"
#include "emFile.h"
#include "UART_PC.h"
#include "Interr_PC.h"
#include "Pin_Relais2_aliases.h"
#include "Pin_Relais2.h"
#include "Pin_Relais1_aliases.h"
#include "Pin_Relais1.h"
#include "Pin_IRLaserEN_aliases.h"
#include "Pin_IRLaserEN.h"
#include "Analog_Digital_Converter_IRQ.h"
#include "Analog_Digital_Converter_theACLK.h"
#include "Analog_Digital_Converter_Bypass_aliases.h"
#include "Analog_Digital_Converter_Bypass.h"
#include "UART_TFT_IntClock.h"
#include "emFile_SPI0.h"
#include "emFile_SPI0_PVT.h"
#include "emFile_mosi0_aliases.h"
#include "emFile_mosi0.h"
#include "emFile_Clock_1.h"
#include "emFile_miso0_aliases.h"
#include "emFile_miso0.h"
#include "emFile_sclk0_aliases.h"
#include "emFile_sclk0.h"
#include "emFile_SPI0_CS_aliases.h"
#include "emFile_SPI0_CS.h"
#include "UART_PC_IntClock.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

